# Generated by Django 3.0.3 on 2020-07-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteLinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug_name',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
