# Generated by Django 3.0.3 on 2020-07-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteLinks', '0002_profile_slug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
